version: "3.2"
services:
  gdal:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_REQUEST_PAYER=requester
    volumes:
      - ./:/data
    command: gdalinfo --version
  gdal_k:
    build:
      dockerfile: Dockerfile_K
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_REQUEST_PAYER=requester
    volumes:
      - ./:/data
    command: gdalinfo --version
