version: "3.2"
services:
  gdal:
    image: geographica/gdal2:2.3.2
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_REQUEST_PAYER=requester
    volumes:
      - ./:/data
    command: gdalinfo --version
  gdal_k:
    image: klokantech/gdal:2.3
    environment:
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_REQUEST_PAYER=requester
    volumes:
      - ./:/data
    command: gdalinfo --version
